# This file was automatically generated by SWIG (https://www.swig.org).
# Version 4.1.0
#
# Do not make changes to this file unless you know what you are doing - modify
# the SWIG interface file instead.

from sys import version_info as _swig_python_version_info
# Import the low-level C/C++ module
if __package__ or "." in __name__:
    from . import _Clexique
else:
    import _Clexique

try:
    import builtins as __builtin__
except ImportError:
    import __builtin__

def _swig_repr(self):
    try:
        strthis = "proxy of " + self.this.__repr__()
    except __builtin__.Exception:
        strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)


def _swig_setattr_nondynamic_instance_variable(set):
    def set_instance_attr(self, name, value):
        if name == "this":
            set(self, name, value)
        elif name == "thisown":
            self.this.own(value)
        elif hasattr(self, name) and isinstance(getattr(type(self), name), property):
            set(self, name, value)
        else:
            raise AttributeError("You cannot add instance attributes to %s" % self)
    return set_instance_attr


def _swig_setattr_nondynamic_class_variable(set):
    def set_class_attr(cls, name, value):
        if hasattr(cls, name) and not isinstance(getattr(cls, name), property):
            set(cls, name, value)
        else:
            raise AttributeError("You cannot add class attributes to %s" % cls)
    return set_class_attr


def _swig_add_metaclass(metaclass):
    """Class decorator for adding a metaclass to a SWIG wrapped class - a slimmed down version of six.add_metaclass"""
    def wrapper(cls):
        return metaclass(cls.__name__, cls.__bases__, cls.__dict__.copy())
    return wrapper


class _SwigNonDynamicMeta(type):
    """Meta class to enforce nondynamic attributes (no new attributes) for a class"""
    __setattr__ = _swig_setattr_nondynamic_class_variable(type.__setattr__)


class Clexique(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self):
        _Clexique.Clexique_swiginit(self, _Clexique.new_Clexique())
    __swig_destroy__ = _Clexique.delete_Clexique

    def g_trans(self, arg2, arg3, arg4):
        return _Clexique.Clexique_g_trans(self, arg2, arg3, arg4)

    def init_trans(self):
        return _Clexique.Clexique_init_trans(self)

    def init_trans_vers(self, arg2):
        return _Clexique.Clexique_init_trans_vers(self, arg2)

    def est_vide(self):
        return _Clexique.Clexique_est_vide(self)

    def nb_desc(self):
        return _Clexique.Clexique_nb_desc(self)

    def met_au_net(self):
        return _Clexique.Clexique_met_au_net(self)

    def enleve(self, arg2):
        return _Clexique.Clexique_enleve(self, arg2)

    def pred(self, *args):
        return _Clexique.Clexique_pred(self, *args)

    def llh(self, *args):
        return _Clexique.Clexique_llh(self, *args)

    def val_max(self, *args):
        return _Clexique.Clexique_val_max(self, *args)

    def read_fich(self, fic, alp=None):
        return _Clexique.Clexique_read_fich(self, fic, alp)

    def read_str(self, fic, alp=None):
        return _Clexique.Clexique_read_str(self, fic, alp)

    def aj_str(self, fic):
        return _Clexique.Clexique_aj_str(self, fic)

    def __str__(self):
        return _Clexique.Clexique___str__(self)

    def ls_num(self):
        return _Clexique.Clexique_ls_num(self)

    def __getitem__(self, i):
        return _Clexique.Clexique___getitem__(self, i)

    def __setitem__(self, i, d):
        return _Clexique.Clexique___setitem__(self, i, d)

    def log_vraisemblance(self, *args):
        return _Clexique.Clexique_log_vraisemblance(self, *args)

    def ecrit_evalue(self, *args):
        return _Clexique.Clexique_ecrit_evalue(self, *args)

# Register Clexique in _Clexique:
_Clexique.Clexique_swigregister(Clexique)

