# This file was automatically generated by SWIG (https://www.swig.org).
# Version 4.1.0
#
# Do not make changes to this file unless you know what you are doing - modify
# the SWIG interface file instead.

from sys import version_info as _swig_python_version_info
# Import the low-level C/C++ module
if __package__ or "." in __name__:
    from . import _Cparti_simp
else:
    import _Cparti_simp

try:
    import builtins as __builtin__
except ImportError:
    import __builtin__

def _swig_repr(self):
    try:
        strthis = "proxy of " + self.this.__repr__()
    except __builtin__.Exception:
        strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)


def _swig_setattr_nondynamic_instance_variable(set):
    def set_instance_attr(self, name, value):
        if name == "this":
            set(self, name, value)
        elif name == "thisown":
            self.this.own(value)
        elif hasattr(self, name) and isinstance(getattr(type(self), name), property):
            set(self, name, value)
        else:
            raise AttributeError("You cannot add instance attributes to %s" % self)
    return set_instance_attr


def _swig_setattr_nondynamic_class_variable(set):
    def set_class_attr(cls, name, value):
        if hasattr(cls, name) and not isinstance(getattr(cls, name), property):
            set(cls, name, value)
        else:
            raise AttributeError("You cannot add class attributes to %s" % cls)
    return set_class_attr


def _swig_add_metaclass(metaclass):
    """Class decorator for adding a metaclass to a SWIG wrapped class - a slimmed down version of six.add_metaclass"""
    def wrapper(cls):
        return metaclass(cls.__name__, cls.__bases__, cls.__dict__.copy())
    return wrapper


class _SwigNonDynamicMeta(type):
    """Meta class to enforce nondynamic attributes (no new attributes) for a class"""
    __setattr__ = _swig_setattr_nondynamic_class_variable(type.__setattr__)


class Cparti_simp(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self):
        _Cparti_simp.Cparti_simp_swiginit(self, _Cparti_simp.new_Cparti_simp())
    __swig_destroy__ = _Cparti_simp.delete_Cparti_simp

    def np_max(self):
        return _Cparti_simp.Cparti_simp_np_max(self)

    def val_max(self):
        return _Cparti_simp.Cparti_simp_val_max(self)

    def nb_seq(self):
        return _Cparti_simp.Cparti_simp_nb_seq(self)

    def lisse(self, *args):
        return _Cparti_simp.Cparti_simp_lisse(self, *args)

    def __getitem__(self, i):
        return _Cparti_simp.Cparti_simp___getitem__(self, i)

    def __str__(self):
        return _Cparti_simp.Cparti_simp___str__(self)

# Register Cparti_simp in _Cparti_simp:
_Cparti_simp.Cparti_simp_swigregister(Cparti_simp)

