# This file was automatically generated by SWIG (https://www.swig.org).
# Version 4.1.0
#
# Do not make changes to this file unless you know what you are doing - modify
# the SWIG interface file instead.

from sys import version_info as _swig_python_version_info
# Import the low-level C/C++ module
if __package__ or "." in __name__:
    from . import _Fmatrice
else:
    import _Fmatrice

try:
    import builtins as __builtin__
except ImportError:
    import __builtin__

def _swig_repr(self):
    try:
        strthis = "proxy of " + self.this.__repr__()
    except __builtin__.Exception:
        strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)


def _swig_setattr_nondynamic_instance_variable(set):
    def set_instance_attr(self, name, value):
        if name == "this":
            set(self, name, value)
        elif name == "thisown":
            self.this.own(value)
        elif hasattr(self, name) and isinstance(getattr(type(self), name), property):
            set(self, name, value)
        else:
            raise AttributeError("You cannot add instance attributes to %s" % self)
    return set_instance_attr


def _swig_setattr_nondynamic_class_variable(set):
    def set_class_attr(cls, name, value):
        if hasattr(cls, name) and not isinstance(getattr(cls, name), property):
            set(cls, name, value)
        else:
            raise AttributeError("You cannot add class attributes to %s" % cls)
    return set_class_attr


def _swig_add_metaclass(metaclass):
    """Class decorator for adding a metaclass to a SWIG wrapped class - a slimmed down version of six.add_metaclass"""
    def wrapper(cls):
        return metaclass(cls.__name__, cls.__bases__, cls.__dict__.copy())
    return wrapper


class _SwigNonDynamicMeta(type):
    """Meta class to enforce nondynamic attributes (no new attributes) for a class"""
    __setattr__ = _swig_setattr_nondynamic_class_variable(type.__setattr__)


class Fmatrice(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self):
        _Fmatrice.Fmatrice_swiginit(self, _Fmatrice.new_Fmatrice())
    __swig_destroy__ = _Fmatrice.delete_Fmatrice

    def carac(self, arg2):
        return _Fmatrice.Fmatrice_carac(self, arg2)

    def g_val(self, arg2, arg3, arg4):
        return _Fmatrice.Fmatrice_g_val(self, arg2, arg3, arg4)

    def recup_rel(self, arg2, arg3, arg4):
        return _Fmatrice.Fmatrice_recup_rel(self, arg2, arg3, arg4)

    def melange(self):
        return _Fmatrice.Fmatrice_melange(self)

    def exponentielle(self):
        return _Fmatrice.Fmatrice_exponentielle(self)

    def log_normalise(self):
        return _Fmatrice.Fmatrice_log_normalise(self)

    def __str__(self):
        return _Fmatrice.Fmatrice___str__(self)

    def __len__(self):
        return _Fmatrice.Fmatrice___len__(self)

    def ndesc(self):
        return _Fmatrice.Fmatrice_ndesc(self)

    def recup_relC(self, C, i, j):
        return _Fmatrice.Fmatrice_recup_relC(self, C, i, j)

    def __call__(self, i, j):
        return _Fmatrice.Fmatrice___call__(self, i, j)

# Register Fmatrice in _Fmatrice:
_Fmatrice.Fmatrice_swigregister(Fmatrice)

